include config.mk

CPPFLAGS = -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_XOPEN_SOURCE=700 -D_GNU_SOURCE -DDEBUG
CFLAGS   = -std=c11 -Og -g
LDFLAGS  = 

W32_GDI_METHOD   = fake
QUARTZ_CG_METHOD = fake
DUMMY_METHOD     = yes
