#!/usr/bin/env python
# -*- mode: python, encoding: utf-8 -*-
# See LICENSE file for copyright and license details.

import sys
import os

with open(os.path.dirname(sys.argv[0]) + '/../lib/libgamma-error.h', 'rb') as file:
    data = file.read()
data = data.decode('utf-8')

if sys.argv[1] == '--list':
    defs = [line for line in data.split('\n') if line.startswith('#define') and not line.endswith('_H')]
    defs = [line.split(' ')[1] for line in defs if 'LIBGAMMA_ERROR_MIN' not in line]
    print('\n'.join(defs))

else:
    i = data.find('\n#define ' + sys.argv[1])
    data = data[:i]
    i = data.rfind('\n */')
    data = data[:i]
    i = data.rfind('/**\n')
    data = data[i + len('/**\n'):]
    data = [line[3:] for line in data.split('\n')]
    print('\n'.join(data))

