#!/usr/bin/env python
# -*- mode: python, encoding: utf-8 -*-

# libgamma -- Display server abstraction layer for gamma ramp adjustments
# Copyright (C) 2014  Mattias Andrée (maandree@member.fsf.org)
# 
# This library is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this library.  If not, see <http://www.gnu.org/licenses/>.

import sys
import os

with open(os.path.dirname(sys.argv[0]) + '/../lib/libgamma-error.h', 'rb') as file:
    data = file.read()
data = data.decode('utf-8', 'error')

if sys.argv[1] == '--list':
    defs = [line for line in data.split('\n') if line.startswith('#define') and not line.endswith('_H')]
    defs = [line.split(' ')[1] for line in defs if 'LIBGAMMA_ERROR_MIN' not in line]
    print('\n'.join(defs))

else:
    i = data.find('\n#define ' + sys.argv[1])
    data = data[:i]
    i = data.rfind('\n */')
    data = data[:i]
    i = data.rfind('/**\n')
    data = data[i + len('/**\n'):]
    data = [line[3:] for line in data.split('\n')]
    print('\n'.join(data))

