#!/usr/bin/env sh
# See LICENSE file for copyright and license details.

beheading="$1"

data="$(cat)"
lines="$(echo "${data}" | wc -l)"
lines=$(expr ${lines} - ${beheading} )

if test $lines -gt 0; then
    echo "$(echo "${data}" | tail -n ${lines})"
fi
