#!/usr/bin/env python
# -*- mode: python, encoding: utf-8 -*-

# libgamma -- Display server abstraction layer for gamma ramp adjustments
# Copyright (C) 2014  Mattias Andrée (maandree@member.fsf.org)
# 
# This library is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this library.  If not, see <http://www.gnu.org/licenses/>.

import sys

data = sys.stdin.read()[:-1]

n = 0
while '`' in data:
    i = data.find('`')
    replacement = '@code{' if n % 2 == 0 else '}'
    data = data[:i] + replacement + data[i + 1:]
    n += 1

print(data)

